spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test     # Replace 'document_db' with your actual database name
    username: root  # Change to your MySQL username
    password: "[password]"  # Change to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Adjust based on your MySQL version
    hibernate:
      ddl-auto: update  # Options: 'validate' | 'update' | 'create' | 'create-drop'
    show-sql: false  # Enables logging of SQL queries in the console
    properties:
      hibernate:
        format_sql: true  # Pretty prints SQL queries

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # Maximum file upload size
      max-request-size: 20MB  # Maximum request size

  security:
    user:
      name: admin  # Default admin username
      password: admin123  # Default admin password

server:
  port: 8080  # Change if needed

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG  # Logs SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Logs query parameters
