package turing.example.documentmanagement.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;

/**
 * Represents a specific version of a document in the document management system.
 * <p>
 * Each document can have multiple versions, and this entity stores information
 * about individual versions, such as the file path, version number, and upload timestamp.
 * </p>
 */
@Entity
@Data
public class DocumentVersion {

    /**
     * Unique identifier for the document version.
     * <p>
     * Auto-generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The file path where this version of the document is stored.
     */
    private String filePath;

    /**
     * Version number of the document.
     * <p>
     * This helps in tracking and managing different versions of the same document.
     * </p>
     */
    private int version;

    /**
     * Timestamp indicating when this version was uploaded.
     */
    private LocalDateTime uploadedAt;

    /**
     * The document associated with this version.
     * <p>
     * Defines a many-to-one relationship with the {@link Document} entity,
     * meaning multiple versions belong to a single document.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "document_id", nullable = false)
    private Document document;
}
