package turing.example.documentmanagement.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Represents a document in the document management system.
 * <p>
 * This entity stores essential metadata about a document, such as its name,
 * owner, creation timestamp, and associated versions.
 * </p>
 */
@Entity
@Data
public class Document {

    /**
     * Unique identifier for the document.
     * <p>
     * Auto-generated by the database using identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the document.
     */
    private String name;

    /**
     * Owner of the document (e.g., username or user ID).
     */
    private String owner;

    /**
     * Timestamp indicating when the document was created.
     */
    private LocalDateTime createdAt;

    /**
     * List of document versions associated with this document.
     * <p>
     * Defines a one-to-many relationship where a document can have multiple versions.
     * CascadeType.ALL ensures that all associated versions are persisted or deleted
     * along with the document.
     * </p>
     */
    @OneToMany(mappedBy = "document", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<DocumentVersion> versions;
}
